# config that builds the env as Yifan had it
run:
  algorithm:
    load_model: False  
    model_path: ""  
    type: "PPO"
    gamma: 0.99
    learning_rate: 0.0003
    custom_policy:
      activation_function: "ReLU"
      value_function:
        - 256
        - 256
        - 256
        - 256
      policy_function:
        - 256
        - 256
        - 256
        - 256
  train:
    num_envs : 16  
    logging: 0
    timesteps: 15000000 
    save_freq : 30000
    save_folder: "./models/weights"  
    save_name: "platexperiment_default"
  eval:
    max_episodes: -1  
    logging: 1  
    display_delay: 0.00416666666 
    show_world_aux: True
    show_goal_aux: True
    show_sensor_aux: False

env:
  max_steps_per_episode: 1024  
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  use_physics_sim: True
  gravity: [0, 0, -9.8]
  sim_step: 0.00416666666 
  sim_steps_per_env_step: 1 
  robots:
    - type: "UR5" 
      config:
        name: "ur5_1"
        base_position: [0, 0, 0]
        base_orientation: [0, 0, 0]
        resting_angles: [-180, -45, -90, -135, 90, 0]
        control_mode: 2
        self_collision: False
      sensors:
        - type: "LidarSensorGeneric"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: False
            indicator_buckets: 15
            ray_start: 0
            ray_end: 0.3
            ray_setup:
              ee_link: 15
              wrist_1_link: 15
              forearm_link: 15
            indicator: True
      goal:
        type: "PositionCollision"
        config:
          add_to_logging: True
          continue_after_success: True
          reward_success: 15
          reward_collision: -5
          reward_distance_mult: -0.05
          dist_threshold_start: 0.3
          dist_threshold_end : 0.025
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: "None"

  world:
    type: "PlateExperiment"
    config:
      workspace_boundaries: [-2, 2, -2, 2, 0, 2]
      plate_dimensions: [0.075, 0.175]