run:
  algorithm:
    load_model: True  
    #model_path: "/home/moga/Desktop/IR-DRL/models/weights/model_trained_voxels.zip"  #only if loaded model is necessary
    model_path: "/home/moga/Desktop/IR-DRL/models/weights/model_19440000_steps.zip"
    type: "PPO"
    config:
      gamma: 0.995
      n_steps: 1024
      ent_coef: 0.008 #TODO: beim nächsten Training rauskommentieren oder auf 0 setzen
      batch_size: 16384
    custom_policy:
      activation_function: "tanh"
      value_function:
        - 256
        - 256
      policy_function:
        - 256
        - 256
        
  train:
    num_envs : 24  
    logging: 0
    timesteps: 150000000 
    save_freq : 90000
    save_folder: "./models/weights"  
    save_name: "s2rexperiment_exp0_1"
  eval:
    max_episodes: -1
    logging: 2 #1 = nach jeder episode eine zeile in die console, 2 = jeder step als zeile in der csv, 3 = das selbe wie 2 aber mit obstacles
    display_delay: 0.00816666666  
    show_world_aux: True
    show_goal_aux: True
    show_sensor_aux: False # Zeigt linien mit Abstand zu obstacles, führt zu warnmeldung debug draw failed

env:
  max_steps_per_episode: 99999999 
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: True
  use_physics_sim: True
  gravity: [0, 0, -9.8]
  sim_step: 0.00416666666 
  sim_steps_per_env_step: 1 
  robots:
    - type: "UR5_Gripper" 
      config:
        name: "ur5_1"
        base_position: [0, 0, 0.01]
        base_orientation: [0, 0, -180]
        resting_angles: [-180, -45, -90, -135, 90, 0]
        control_mode: 1 #0 = 6er vektor (x,y,z,r,p,y), 1 = joint angles direct len vektor = anzahl roboter joints oder eingabe bei control_joints (siehe unten), 2= joint velocities
        self_collision: True
        controlled_joints: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint"]
      sensors:
        - type: "Obstacle"
          config:
            num_obstacles: 1
            max_distance: 0.2 # Distance in which obstacles are detected
            sphere_coordinates: False
            report_velocities: False
            reference_link_ids: ["ee_link", "forearm_link", "wrist_1_link", "wrist_2_link", "wrist_3_link"]
            extra_points_link_pairs: [["forearm_link", "wrist_1_link", 1], ["forearm_link", "upper_arm_link", 1]]
        - type: "ObstacleAbsolute"
          config:
            num_obstacles: 1
            max_distance: 0.4
            report_velocities: False
        - type: "RobotSkeleton"
          config:
            report_velocities: False
            reference_link_ids: ["ee_link", "forearm_link", "wrist_1_link", "wrist_2_link", "wrist_3_link"]
            extra_points_link_pairs: [["forearm_link", "wrist_1_link", 1], ["forearm_link", "upper_arm_link", 1]]
      goal:
        type: "PositionCollisionNoShakingProximityV2"
        config:
          add_to_logging: True
          continue_after_success: True
          dist_threshold_start: 0.4
          dist_threshold_end : 0.05
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: 0.05
          d_min: 0.08
          reward_success: 150
  world:
    type: "Generated"
    config:
      workspace_boundaries: [-2, 2, -2, 2, -1, 5]
      obstacles:
      - type: "box"  # tisch
        position: [0.25, 0.25, -0.5]
        rotation: [0, 0, 0]
        params:
          halfExtents: [0.3, 0.3, 0.5]
          seen_by_obstacle_sensor: True
